apiVersion: v1
kind: TEST
metadata:
  name: TEST
data:
  APP_NAME: TEST
  IMAGE_NAME: TEST
  IMAGE_TAG: "TEST"
  CONTAINER_PORT: "12345"
---
kind: ConfigMap
metadata:
  name: sample-app-config
data:
  APP_NAME: sample-app
  IMAGE_NAME: nginx
  IMAGE_TAG: "1.23"
  CONTAINER_PORT: "80"
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
type: Opaque
data:
  DB_USERNAME: JztsfiFAIyQlXiYqKCkoKV9Qe09MOiI8PjxoMT5hYWFhYTxoMT4=  # base64("sample_user")
  DB_PASSWORD: JztsfiFAIyQlXiYqKCkoKV9Qe09MOiI8PjxoMT5hYWFhYTxoMT4=  # base64("securepass")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: nginx:1.23
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sample-app-config
            - secretRef:
                name: sample-app-secret
