apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  annotations:
    note: "<h1>test</h1>"
data:
  APP_NAME: "<h1>test</h1>"
  IMAGE_NAME: "nginx<h1>test</h1>"
  IMAGE_TAG: "1.23<h1>test</h1>"
  CONTAINER_PORT: "80<h1>test</h1>"
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
  annotations:
    note: "<h1>test</h1>"
type: Opaque
data:
  DB_USERNAME: JztsfiFAIyQlXiYqKCkoKV9Qe09MOiI8PjxoMT5hYWFhYTxoMT4=   # base64("sample_user<h1>test</h1>")
  DB_PASSWORD: JztsfiFAIyQlXiYqKCkoKV9Qe09MOiI8PjxoMT5hYWFhYTxoMT4=   # base64("securepass<h1>test</h1>")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: nginx:1.23
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sample-app-config
            - secretRef:
                name: sample-app-secret
